import type { Metadata } from 'next';
import { Footer, IsOnTelegram } from '@/components';
import { Header, MenuBar } from '@/components/applications';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      {/* <IsOnTelegram> */}
      <section className='bg-gradient-2 text-white'>
        <Header />
        <div className='flex flex-col bg-gradient p-4 mb-20'>{children}</div>
        <MenuBar />
      </section>
      {/* </IsOnTelegram> */}
    </div>
  );
}
